version: "3"

services:
  postgres:
    image: "postgres:13"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - .data/postgres:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: always
    networks:
      - bridge-network

  dubheos-bridge-backend:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/postgres
      - DUBHEOS_INDEXER_URL=http://host.docker.internal:3001
      - DUBHEOS_INDEXER_WS_URL=ws://host.docker.internal:3001
      - DUBHEOS_HTTP_RPC=http://host.docker.internal:9944
      - DUBHEOS_BRIDGE_MANAGER_PASSWORD=
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - postgres
    networks:
      - bridge-network

networks:
  bridge-network:
    driver: bridge
